import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import {cn} from '@/lib/utils'
import { Toaster } from "@/components/ui/sonner"

const fontSans = FontSans({
  subsets: ['latin'],
  variable:"--font-sans"
})

export const metadata: Metadata = {
  title: "Clashing APP",
  description: "Generated by create ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
        "w-3/4 min-h-screen bg-slate-400 font-sans antialiased mx-auto mt-4"
      )}>
         <Toaster richColors position="top-right" />
        {children}
      </body>
    </html>
  );
}
